# Generated by Django 4.2.4 on 2023-08-10 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_starships_alter_planet_created_people_starship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 1, 40, 53, 976156, tzinfo=datetime.timezone.utc)),
        ),
    ]
